### ISSUE TITLE
Every time a program where this library is used is closed, the clipboard resets

### ISSUE THREAD

**Issue by liamtoaldo** [d-tsuji/clipboard#2]

**Comment by d-tsuji** [comment]
@Gyro7 
Thanks for trying it out, and as I mentioned with WIP, I have seen the clipboard being reset on Linux.

What is your OS?

**Comment by liamtoaldo** [comment]
> @Gyro7
> Thanks for trying it out, and as I mentioned with WIP, I have seen the clipboard being reset on Linux.
> 
> What is your OS?

I have Feren OS, a Linux distribution based on Ubuntu 20.04

**Comment by d-tsuji** [comment]
Sorry, it's broken. It is recommended to use [atotto/clipboard](https://github.com/atotto/clipboard).

**Comment by liamtoaldo** [comment]
> Sorry, it's broken. It is recommended to use [atotto/clipboard](https://github.com/atotto/clipboard).

That library doesn't work for me, I've already tried it, that's why I'm using yours.
